version: '3'
services:
  backend:
    build:
      context: ./backend   # O diretório onde está o Dockerfile do backend
    ports:
      - "3001:3001"  # Mapeia a porta do host para a porta do contêiner

  frontend:
    build:
      context: ./calendar   # O diretório onde está o Dockerfile do frontend
    ports:
      - "3000:3000"   # Mapeia a porta do host para a porta do contêiner
