name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16,20]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"
        cache-dependency-path: "backend"

    - name: Install Backend Dependencies
      working-directory: backend
      run: npm i

    - name: Test Backend
      working-directory: backend
      run: |
        echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
        echo "USER=${{ secrets.USER }}" >> $GITHUB_ENV
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
        npm test

    #- name: Install Frontend Dependencies
    #  working-directory: ../calendar  # Define o diretório onde estão os arquivos do frontend
    #  run: npm ci

    #- name: Build Frontend
    #  working-directory: ../calendar
    #  run: npm run build --if-present

    #- name: Test Frontend
    #  working-directory: ../calendar
    #  run: npm test
